### ISSUE TITLE
Create a Grade build flavor for F-Droid

### ISSUE THREAD

**Issue by Spikatrix** [Spikatrix/LRC-Editor#15]
Need to figure out how to create a new Gradle flavor for F-Droid as recommended by them. 

For that, I'll need to improve my Gradle-fu once I get time.

**Comment by CarlEidon** [comment]
Consider it done. 👍

**Comment by Spikatrix** [comment]
Working on this. It's happening boys!

**Comment by Spikatrix** [comment]
Done with creating relevant build flavors  
PR: #17 

This issue will be closed once the app has been published to F-Droid

**Comment by Spikatrix** [comment]
Will be available on F-Droid soon. It's marked as ready. Waiting for a package manager to package it.
[Package request link](https://gitlab.com/fdroid/rfp/-/issues/1422)

**Comment by Spikatrix** [comment]
Update: MR was made by a user 2 weeks ago and it has been merged today. It should appear in F-Droid soon :tada:

**Comment by Spikatrix** [comment]
Aaand [it's on F-Droid](https://f-droid.org/packages/com.cg.lrceditor/)!

**Comment by IzzySoft** [comment]
Congrats! Shall I then remove it [from my repo](https://apt.izzysoft.de/fdroid/index/apk/com.cg.lrceditor) (as I usually do once an app appears in "F-Droid proper", to avoid confusion)?

**Comment by Spikatrix** [comment]
@IzzySoft Yes, you can remove it. Thanks for the help!

**Comment by IzzySoft** [comment]
Gladly! And thanks for confirming. Removal will take effect with the next sync in about 8h. Should you need it back for some reason, just yell :wink:
