### ISSUE TITLE
Broken format in Persian locale

### ISSUE THREAD

**Issue by danialbehzadi** [Spikatrix/LRC-Editor#25]
If you edit lyrics times when the device is in Persian locale, the saved file would be broken. I think that's because the times are stored in the file with Persian script (۰, ۱,…,۹) instead of Latin ones (0, 1,…9).
Timestamps should be forced to be saved with Latin script.

**Comment by Spikatrix** [comment]
Thanks for notifying!

I've managed to reproduce the issue. Will be fixed.
