### ISSUE TITLE
"Player not ready"

### ISSUE THREAD

**Issue by SArsalanK** [Spikatrix/LRC-Editor#26]
I try to Edit and then Play the .lrc File and it pops up this message every time "Player not ready"!

![Screenshot_2020-09-28-18-54-39-862_com cg lrceditor](https://user-images.githubusercontent.com/2125947/94441473-3d5e4600-01bc-11eb-9fa9-85b3fa112490.jpg)

**Comment by Spikatrix** [comment]
You need to add a song before playing. Tap on "Tap here to select a song" or the play button at the bottom and select a song. Once the song has been loaded, you'll be able to play each lyric line.

**Comment by SArsalanK** [comment]
I see. Thanks.
