### ISSUE TITLE
dark mode?

### ISSUE THREAD

**Issue by Jan69** [Spikatrix/LRC-Editor#32]
the app is nice and all, only lyric editor I've seen on f-droid, but I'd like to not burn my eyes off interacting with it e.g. morning/evening/rainy day when it migh be nice to chill in dark, but not so nice to need inverting whole system colors

**Comment by Spikatrix** [comment]
Both the F-Droid and Google Play versions have support for dark themes. To unlock it from the Google Play version, all that needs to be done is to complete any in-app purchase (IAP) from within the app. The F-Droid version, as you know, does not have any IAPs as they are proprietary which means that there's no way to unlock the dark themes.

What you can do instead, is build the app from source with dark themes enabled.

**Comment by SodaWithoutSparkles** [comment]
Some phones have force dark-mode for apps. It is not perfect but good enough. It basically invert colours of text and background. Not great, but at least it wont blind your eyes anymore. @Jan69
